services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html/
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html/
